name: release-tag

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Install xmllint
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libxml2-utils

    - name: Update nuspec
      run: |
        xmllint --shell xml2rfc.nuspec << EOF
        setns ns=http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd
        cd /ns:package/ns:metadata/ns:version
        set ${{ github.event.inputs.next_version }}
        save
        exit
        EOF

    - name: Push commit and tag
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
        git add xml2rfc.nuspec
        git commit -m "Bump version to ${{ github.event.inputs.next_version }}"
        git tag v${{ github.event.inputs.next_version }}
        git push origin HEAD:${GITHUB_REF} --tags
